packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js: false
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true
  puppeteer: false
  unrs-resolver: true
