// The pdfmake WebView harness HTML, inlined as a string at build time by the
// `inline-import` babel plugin (extensions includes '.html'). Generated by
// scripts/build-pdf-harness.mjs — run `pnpm build:pdf-harness` to regenerate
// after a pdfmake upgrade. Relative path (not the @/ alias) so the babel plugin
// resolves it reliably.
import html from '../assets/pdf/pdfHarness.html'

// Cache-bust marker: bump this whenever you re-run `pnpm build:pdf-harness`.
// Metro caches this module's transform keyed on THIS file's source, not on the
// inlined .html — so changing only the .html won't invalidate the cache. Editing
// this comment forces a re-transform that re-reads the fresh harness.
// harness-rev: 3
export default html
