// The pdf.js viewer harness HTML, inlined as a string at build time by the
// `inline-import` babel plugin (extensions includes '.html'). Generated by
// scripts/build-pdf-viewer.mjs — run `pnpm build:pdf-viewer` to regenerate
// after a pdfjs-dist upgrade. Relative path (not the @/ alias) so the babel
// plugin resolves it reliably.
import html from '../assets/pdf/pdfViewer.html'

// Cache-bust marker: bump this whenever you re-run `pnpm build:pdf-viewer`.
// Metro caches this module's transform keyed on THIS file's source, not on the
// inlined .html — so changing only the .html won't invalidate the cache.
// viewer-rev: 2
export default html
